// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu657Xkylg_vFM0KSto_yajQuFjrTjrD4',
    appId: '1:522123866552:web:6eaefbcf47349b07a6df4d',
    messagingSenderId: '522123866552',
    projectId: 'amentware-exper',
    authDomain: 'amentware-exper.firebaseapp.com',
    storageBucket: 'amentware-exper.firebasestorage.app',
    measurementId: 'G-9XD9W0PDN7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeYc7g03ao-RE2jQgR7WQz_YTg_x1bC_4',
    appId: '1:522123866552:android:33b1467a6711bc79a6df4d',
    messagingSenderId: '522123866552',
    projectId: 'amentware-exper',
    storageBucket: 'amentware-exper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwYy9neTkJox9EXd1CcffatQZFUwQ6lcU',
    appId: '1:522123866552:ios:ada778b70db3823ca6df4d',
    messagingSenderId: '522123866552',
    projectId: 'amentware-exper',
    storageBucket: 'amentware-exper.firebasestorage.app',
    iosBundleId: 'com.example.exper',
  );
}
